version: '3.8'

services:
  juice-shop-1:
    image: bkimminich/juice-shop
    expose:
      - "3000"
    #ports:
    #- "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"  
          memory: "512M"

  juice-shop-2:
    image: bkimminich/juice-shop
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  juice-shop-3:
    image: bkimminich/juice-shop
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - juice-shop-1
      - juice-shop-2
      - juice-shop-3
